source 'https://rubygems.org'

gem 'bitters'
gem 'builder', '~> 3.0'
gem 'bourbon'
gem 'middleman', '~> 3.3.3'
gem 'middleman-blog', '~> 3.5.3'
gem 'middleman-gh-pages'
gem 'middleman-livereload'
gem 'neat'
gem 'nokogiri'
gem 'rack-contrib'
gem 'redcarpet'
